# Site-wide settings
# ------------------

title: the-journal
subtitle: homepage

author:
  name: Linh Vu (linhvth)
  email: linhvth (dot) contact (at) gmail (dot) com

url: "https://linhvth.github.io"
baseurl: "/the-journal"
# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
description: |
  This is a logbook for ongoing prior-posterior updates, 
  where I record my assumptions and test them against experience.

disqus:
  shortname: linhvth-thejournal

paginate: 5
paginate_path: "/blog/page:num/"
# Build settings
# --------------

# If you wish to use the gem-version of Minima with or without a Gemfile, use
#   the following setting:
# theme: minima

# **OR** if you wish to use the theme directly from the GitHub repository by
#   bypassing a Gemfile, use the following setting instead.
#   It is best that you lock to a particular commit and update if uptream changes
#   do not affect your site adversely.
remote_theme: jekyll/minima@d4d779a

# Minima requires the following plugins:
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-archives

jekyll-archives:
  enabled:
    - tags
  layout: tag_archive
  permalinks:
    tag: '/tag/:name/'
    
# Uncomment the following setting if you wish to disable deprecation warnings
#   from newer versions of sass converter. Adapt as required.
sass:
  quiet_deps: true
  silence_deprecations: [import]

# Minima-specific settings (applicable to Minima v3 and above only)
# -----------------------------------------------------------------

#  *All described config keys below should be nested under the top-level
#   `minima` key.*

minima:
  # Minima skin selection. Available skins are:
  #   * classic            Default, light color scheme.
  #   * dark               Dark variant of the classic skin.
  #   * auto               Adaptive skin based on the classic and dark skins.
  #   * solarized-light    Light variant of solarized color scheme.
  #   * solarized-dark     Dark variant of solarized color scheme.
  #   * solarized          Adaptive skin for solarized color scheme skins.
  skin: classic

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this
  #   and list the `path` property (as represented via Liquid) of the pages in
  #   the order they should be rendered.
  nav_pages:
    - about.md
    - bookmarks.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: true

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values
  date_format: "%b %d, %Y"

  # Social Media Links.
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of
  #   entries. Valid entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
  social_links:

  # Hide syndication feed subscription link.
  #   RSS / Atom feed link is always rendered as the last item of social-links
  #   list. Set below key to `true` to not have the link to feed rendered as
  #   part of social-links list.
  hide_site_feed_link: true
